### ISSUE TITLE
comparing a NLP model to CheXbert

### ISSUE THREAD

**Issue by saboof** [stanfordmlgroup/CheXbert#1]
Hi, 

Assuming I own a NLP labeling function and I want to compare the performance of my model to CheXbert. Is there a way to  get access to this CheXpert reports dataset?

All The Best,

**Comment by akshaysmit** [comment]
Hi,

It turns out that the CheXpert radiology reports, as of now, contain PHI  (protected health information) that we unfortunately cannot share externally. 

Apologies.

**Comment by saboof** [comment]
Hi, 

To still allow some comparison, can you share the distribution of findings across these 1000 reports?

**Comment by saahil9jain** [comment]
Hi,
Unfortunately, we cannot share the distribution of findings, as this may affect the CheXpert competition. If this changes, we will be sure to update. However, the CheXpert training dataset is publicly available, and the distribution of findings (positive, negative, uncertain) should be roughly similar to that. We hope that can be useful for you.
