### ISSUE TITLE
building the conda environment

### ISSUE THREAD

**Issue by ryan-wolbeck** [stanfordmlgroup/CheXbert#2]
Hello,
I'm trying to build the environment from the environment.yml you have in the repo but I'm getting the following.

```bash
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - pyzmq==18.1.1=py37he6710b0_0
  - libgcc-ng==9.1.0=hdf63c60_0
  - glib==2.63.1=h5a9c865_0
  - gst-plugins-base==1.14.0=hbbd80ab_1
  ...

```

I think this is due to the fact that if they don't already exist in the conda environment ResolvePackageNotFound will throw this error similar to this post

https://stackoverflow.com/questions/49154899/resolvepackagenotfound-create-env-using-conda-and-yml-file-on-macos

I'm thinking you might need to move all dependancies to the pip section but I'm not positive. I'm attempting to setup on MacOS

Thanks,
Ryan

**Comment by saahil9jain** [comment]
Hi Ryan, I added a requirements.txt file. Let me know if this helps.
