### ISSUE TITLE
Releasing ID/Labels of Manually Annotated Reports from MIMIC-CXR?

### ISSUE THREAD

**Issue by tianranzhang** [stanfordmlgroup/CheXbert#3]
In the paper you used 687 manually annotated MIMIC-CXR reports to evaluate your models, since MIMIC-CXR is already publicly available, is it possible to release the study id and manual annotation of the said 687 reports?
Thanks!

**Comment by saahil9jain** [comment]
Hi,
Thanks for asking and for your patience! We will need to get approval from our annotators and collaborators. If this is possible, we will be sure to release them and update you.

Best,
Saahil

**Comment by saahil9jain** [comment]
@rajpurkar, let me know if you know of permissions regarding data sharing that would make this possible.

**Comment by tianranzhang** [comment]
> @rajpurkar, let me know if you know of permissions regarding data sharing that would make this possible.



> Hi,
> Thanks for asking and for your patience! We will need to get approval from our annotators and collaborators. If this is possible, we will be sure to release them and update you.
> 
> Best,
> Saahil

Hi Saahil!
Thanks for looking into it.
I wanted to follow up on this and see if there is any chance I could make use of this labeled dataset in my research.
Please let me know.

Thanks,
Tianran

**Comment by saahil9jain** [comment]
Hi Tianran,
Thanks for following up. I looked into it - unfortunately, we can't share this data externally yet, as it depends on securing permissions from other institutions. It seems unlikely that we will be able to release it at the moment, but I will let you know if we can do so at some point.

Best,
Saahil
